=== Maged-Samir/System-Development-Labs-ITI/XML/Day 02/myFamily.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="uncle" type="xs:string"/>
	
	<xs:element name="aunt">
	<xs:complexType>
	<xs:simpleContent>
		<xs:extension base="xs:string">
		<xs:attribute name="sons" type="xs:integer"  use="required"/>
		</xs:extension>
	</xs:simpleContent>
	</xs:complexType>
	</xs:element>
	
	<xs:element name="son">
	<xs:complexType>
	<xs:simpleContent>
		<xs:extension base="xs:string">
		<xs:attribute name="age" type="xs:integer"  use="required"/>
		<xs:attribute name="sport" type="xs:string"  use="required"/>
		</xs:extension>
	</xs:simpleContent>
	</xs:complexType>
	</xs:element>
	
	<xs:element name="daughter">
	<xs:complexType>
	<xs:simpleContent>
		<xs:extension base="xs:string">
		<xs:attribute name="age" type="xs:string"  use="required"/>
		<xs:attribute name="job" type="xs:string"  use="required"/>
		</xs:extension>
	</xs:simpleContent>
	</xs:complexType>
	</xs:element>
	
	<xs:element name="mother">
	<xs:complexType>
	<xs:simpleContent>
		<xs:extension base="xs:string">
		<xs:attribute name="name" type="xs:string"  use="required"/>
		</xs:extension>
	</xs:simpleContent>
	</xs:complexType>
	</xs:element>
	

<xs:element name="father">
<xs:complexType mixed="true">
<xs:sequence>
<xs:element name="mother">
<xs:complexType>
<xs:simpleContent>
	<xs:extension base="xs:string">
	<xs:attribute name="name" type="xs:string"/>
	</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>

<xs:element name="daughter" >
<xs:complexType>
<xs:simpleContent>
	<xs:extension base="xs:string">
	<xs:attribute name="age" type="xs:string"/>
	<xs:attribute name="job" type="xs:string"/>
	</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="son" >
<xs:complexType>
<xs:simpleContent>
	<xs:extension base="xs:string">
	<xs:attribute name="age" type="xs:integer"/>
	<xs:attribute name="sport" type="xs:string"/>
	</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
</xs:sequence>
<xs:attribute name="job" type="xs:string"/>
</xs:complexType>
</xs:element>		
	



<xs:element name="family">
<xs:complexType>
<xs:sequence>
<xs:element ref="grandfather"/>
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
	
	<xs:element name="grandfather">
<xs:complexType mixed="true">
<xs:sequence>
<xs:element ref="father"/>
 <xs:element ref="uncle" maxOccurs="2"/>
 <xs:element ref="aunt" />
</xs:sequence>
<xs:attribute name="name" type="xs:string"/>
</xs:complexType>
</xs:element>
	
	
</xs:schema>

=== Maged-Samir/System-Development-Labs-ITI/XML/Day 02/family.xml
<?xml-stylesheet type="text/css" href="display.css"?>
<family name="myfamilytree" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="myFamily.xsd">
	<!--<!DOCTYPE family SYSTEM "family.dtd">-->
	<grandfather>Ibrahim
            <father job="Engineer">ali
               <mother name="Hoda"></mother>
			   <daughter age="medium" job="ITIstudent">Kareema</daughter>
			   <son age="21" sport="football">mohamed</son>
		    </father>
		<uncle>abd el fatah</uncle>
		<uncle>reda</uncle>
		<aunt sons="2">layla</aunt>
	</grandfather>
</family>
