=== Maged-Samir/System-Development-Labs-ITI/XML/Day 01/task 01/MyDocType.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT family (grandfather*)>
<!ELEMENT grandfather (#PCDATA | father | uncle | aunt)*>
<!ELEMENT father (mother,daughter*,son)>
<!ELEMENT uncle (#PCDATA)>
<!ELEMENT aunt (#PCDATA)>
<!ELEMENT son (#PCDATA)>
<!ELEMENT mother (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT child (#PCDATA)>
<!ATTLIST father job CDATA #REQUIRED name CDATA #REQUIRED >
<!ATTLIST son age CDATA #REQUIRED sport CDATA #REQUIRED >
<!ATTLIST aunt sons CDATA #REQUIRED>
<!ELEMENT daughter (#PCDATA | name |child)*>
<!ATTLIST daughter job CDATA #REQUIRED age CDATA #REQUIRED >

=== Maged-Samir/System-Development-Labs-ITI/XML/Day 01/task 01/family3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "MyDocType.dtd">
<family>
	<grandfather>ibrahim
            <father job="Engineer" name="Ali">
			<mother>
				<name> mona</name>
			</mother>
			<daughter age="23 years old" job="ITI 		       student">ghada</daughter>
			<daughter job="IT Specialist" age="30 years old">
			     <name> Ola</name>
			     <child>karim</child>
			</daughter>
			<son age="21" sport="football">mohamed</son>
		</father>
		<uncle>abd el fatah</uncle>
		<uncle>reda</uncle>
		<aunt sons="2">labiba</aunt>
	</grandfather>
</family>
