=== Maged-Samir/System-Development-Labs-ITI/XML/Day 01/task 02/myPOrder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT purchaseOrder (shipTo,billTo,items,ship_date,ship_method)>
<!ELEMENT shipTo (name,street,city,state,zip)>
<!ELEMENT billTo (name,street,city,state,zip)>
<!ELEMENT ship_date (#PCDATA)>
<!ELEMENT ship_method (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT items (item*)>
<!ELEMENT item (productName,quantity,USPrice)>
<!ELEMENT productName (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT USPrice (#PCDATA)>
<!ATTLIST purchaseOrder orderDate CDATA #REQUIRED>
<!ATTLIST shipTo country CDATA #REQUIRED>
<!ATTLIST billTo country CDATA #REQUIRED>
<!ATTLIST item partNum CDATA #REQUIRED>
<!ATTLIST ship_method type CDATA #REQUIRED>

=== Maged-Samir/System-Development-Labs-ITI/XML/Day 01/task 02/POrder.xml
<?xml version="1.0"?>
<!DOCTYPE purchaseOrder SYSTEM "myPOrder.dtd">
<purchaseOrder orderDate="20th of October 1999" >
	<shipTo country="Dubai">
		<name>Alice Smith</name>
		<street>123 Maple Street</street>
		<city>Mill Valley</city>
		<state>CA</state>
		<zip>90952</zip>
	</shipTo>
	<billTo country="Dubai">
		<name>Robert Smith</name>
		<street>8 Oak Avenue</street>
		<city>Old Town</city>
		<state>PA</state>
		<zip>95819</zip>
	</billTo>
	
	<items>
		<item partNum="AA-150">
			<productName>Lawnmower</productName>
			<quantity>1</quantity>
			<USPrice>148.95</USPrice>
		</item>
		<item partNum="AA-160">
			<productName>Baby Monitor</productName>
			<quantity>1</quantity>
			<USPrice>39.98</USPrice>
		</item>
	</items>
	<ship_date>30-10-1999</ship_date>
	<ship_method type="Shipping"/>
</purchaseOrder>
